name: Build and Deploy
on: [push]
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/README.md') }}
          restore-keys: pip-${{ runner.os }}
      - name: Install Python dependencies
        run: python -m pip install docker-compose humanfriendly conan conan-package-tools
  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - name: CentOS 6 GCC 7 x86_64
        env:
          GCC_VERSIONS: "7"
          DOCKER_ARCHS: "x86_64"
          DOCKER_DISTRO: "centos6,jnlp-slave-centos6"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: python build.py
      - name: CentOS 6 GCC 7 x86
        env:
          GCC_VERSIONS: "7"
          DOCKER_ARCHS: "x86"
          DOCKER_DISTRO: "centos6,jnlp-slave-centos6"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: python build.py
      - name: Ubuntu MinGW GCC 7 x86_64
        env:
          GCC_VERSIONS: "7"
          DOCKER_ARCHS: "x86_64"
          DOCKER_DISTRO: "mingw"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: python build.py
      - name: Conan Server
        env:
          BUILD_CONAN_SERVER_IMAGE: 1
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: python build.py
      - name: Conan Tests
        env:
          BUILD_CONAN_TESTS: 1
          BUILD_CONAN_TEST_AZURE: 1
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: python build.py
